railsapp/config/routes.rb
Rails.application.routes.draw do

  #devise login signup
  devise_for :users
  #edit-user
  post "users/edit_profiles", to: "users#edit_profiles",as: 'users/edit_profiles'

  #root
  root 'photos#index'

  #photos
  get 'new', to: 'photos#new'
  delete 'photos/:id', to: 'photos#destroy', as: 'photos/destroy'
  
  #albums
  get "albums/add/:id", to: "albums#add", as: 'albums/add'
  #photos, albums
  resources :photos , :albums
  # profiles
  get 'profiles/albums/:id', to: 'profiles#show_albums', as: 'profiles/album'
  get 'profiles/show/:id', to: 'profiles#show', as: 'profiles/show'
  get 'profiles/following/:id', to: 'profiles#show_following', as: 'profiles/following'
  get 'profiles/follower/:id', to: 'profiles#show_follower', as: 'profiles/follower'
  post 'profiles/following-connect/:id', to: 'profiles#follow_connect', as: 'profile/following-connect'
  delete 'profiles/following-delete/:id', to: 'profiles#follow_destroy', as:'profile/following-delelte'
  
  #reaction
  get "reactions/react-photo/:id", to: "reactions#react_photo", as: 'reactions/react-photo'
  get "reactions/unreact-photo/:id", to: "reactions#unreact_photo", as: 'reactions/unreact-photo'
  get "reactions/react-album/:id", to: "reactions#react_album", as: 'reactions/react-album'
  get "reactions/unreact-album/:id", to: "reactions#unreact_album", as: 'reactions/unreact-album'

  #discover
  get "discover/photos", to: "discover#show_photos", as: 'discover/photos'
  get "discover/albums", to: "discover#show_albums", as: 'discover/albums'
end

railsapp/app/models/photo.rb
class Photo < ApplicationRecord
    has_many :albums_photos, dependent: :destroy
    has_many :albums, through: :albums_photos
   
    
    belongs_to :user,  counter_cache: :photos_count
    has_many :reactions ,as: :react, dependent: :destroy

    # validates :title, :desc, :status, :image, presence: true
    # validates :title, length: {maximum:140}
    # validates :desc, length: {maximum:300}
    # validates :status, acceptance: {accept: ['1','0']}
    # validates :image, format: {with: /\.(png|jpeq|gif)\Z/i}
    # validate :image_size_validation
    

    #upload picture
    mount_uploader :image, ImageUploader
    
    private
    def image_size_validation
        errors[:image] << "should be less than 5MB" if :image.size > 5.megabytes
    end
    
end

railsapp/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_id_photo, only: [:edit,:update,:destroy]
  
  def index
    if current_user
      @photos= Photo.joins("INNER JOIN follows ON follows.follower_id = user_id").where("follows.followed_id = :id", id: current_user.id).page params[:page]
    else
      @photos= Photo.where("status = ?",'1').order(:created_at).includes(:user,:reactions).page params[:page]
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.new params_photo
    if @photo.save
      flash[:success] = "Upload success"
      redirect_to photos_path
    else
      flash[:danger] = "Register failed"
      render :new
    end
  end
  def edit
     
  end
  def update
    if @photo.update(params_photo)
      flash[:success] = 'The photo has just updated'
      redirect_to profiles_show_path(current_user)
    else
      render 'edit'  
    end
  end
  
  def destroy
    @photo.destroy
    redirect_to profiles_show_path(current_user.id)
  end
  private
  def params_photo
    params.require(:photo ).permit(:title, :desc,:status,:image)
  end

  def find_id_photo
    @photo = Photo.find(params[:id])
  end
  
  
end

railsapp/app/helpers/photos_helper.rb
module PhotosHelper
end

railsapp/app/views/photos/edit.html.erb
<div class="container">
    <div class="card ">
        <div class="row photos_to_albums">
            <div class="col-sm-8">
                <%= form_for @photo, html: {class: "form-horizontal"} do |f| %>
                    <div class="form-group">
                            <%= f.label :title, "Title of Picture", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
                        </div>
                    </div>
                    <div class="form-group">
                            <%= f.label :desc, "Description", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :desc, class: "form-control", placeholder: "Enter description" %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="picture">
                            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/jpg" %>
                        </div>
                    </div>

                    <%= f.select :status, options_for_select([["Public", "1"],["Private", "0"] ]), :class => 'genForm_dropBox' %>


                    <div class="form-group">
                        <div class="col-md-10">
                            <%= f.submit "Update", class: "btn btn-success" %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <div class="btn btn-danger"><%= link_to 'Destroy', @photo,  method: :delete %></div>    
                        </div>
                    </div>
                   <img src=<%=@photo.image%>>
                <% end %>
            </div>
        </div>
    </div>
</div>

railsapp/app/views/photos/index.html.erb
<div class="container-fluid cus-body-color">
  <div class="row">
    <div class="col-12 col-sm-2 sticky-top ">
      <ul class="list mt-4 submenu ">
        <li><%= link_to "Feed",  photos_path, class: 'feed-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'discover-submenu' %></li>
      </ul>
    </div>
    <div class="col-12 col-sm-8 pt-4 cus-card-color">
      <div class="photos_to_albums">
        <div class="btn-group btn-group-lg but" role="group" aria-label="Basic example">
          <button type="button" class="btn pagebut " style="background:#3c5a96; color:#FFF">Photos</button>
          <button type="button" class="btn pagebut" style="border: 2px solid #3c5a96"><%= link_to "Albums", albums_path, {style: 'font-size: 20px;  color: #3c5a96 ; text-decoration: none' } %></button>
        </div>
      </div>

      <div class="container cus-main op">
        <div class="row mt-4">
          <% @photos.each do |photo|%>
          <div class="col-12 col-sm-12 col-md-12 col-lg-6 photo-container">
            <div class="card mb-3 shadow" style="max-width: 540px;">
              <div class="row no-gutters">
                <div class="col-md-12 col-lg-7">
                  <img src=<%= photo.image_url(:thumb)%> class=" cus" alt="..." data-toggle="modal" data-target="#mod">
                </div>

                <div class="col-md-12 col-lg-5">
                  <div class="card-body cus-body">
                 
                    <div  class="user d-flex">
                        <div class="image"> 
                          <%=photo.user.fname.slice(0)+photo.user.lname.slice(0)%>    
                        </div>
                         <%= link_to profiles_show_path(photo.user.id) do %> 
                      <span class=" "><%= photo.user.fname%> <%=photo.user.lname %></span>
                      <% end%>  
                    </div>
                     
                    <h5 class="card-title custitle" ><%= photo.title%></h5>
                    <p class="card-text cusdesc " ><%= photo.desc%></p>
                  </div>
                  <div>
                  <% if user_signed_in? %>
                      <% if photo.reactions.exists? user_id: current_user.id%>
                        <%= link_to reactions_unreact_photo_path(photo.id) do %>
                          <i class="fas fa-heart fa-1x">&nbsp;<%= photo.reactions.size%></i>
                        <% end%> 
                      <%else%>
                        <%= link_to reactions_react_photo_path(photo.id) do %>
                          <i class="far fa-heart fa-1x">&nbsp;<%= photo.reactions.size%></i>
                        <% end%> 
                      <% end%> 
                  <% end%> 
                    <i class="card-text"><small class="cusdate pt-1"><%= photo.created_at%></small></i>
                  </div>
                </div>

              </div>
            </div>
          </div>
            <% end%>
        </div>
      </div>
    </div>
  </div>
</div>
             


<!-- Modal -->
<div class="modal fade" id="mod" tabindex="-1" role="dialog" aria-labelledby="modal-title-id" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-title-id">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img id="modal-img" src="" alt="..." style="width:100%;height:auto">
      </div>
      <div class="modal-footer">
       <p id="modal-desc"></p>
      </div>
    </div>
  </div>
</div>
<div class="photos_to_albums"> <%= paginate @photo, theme: 'twitter-bootstrap-4' %></div>

railsapp/app/views/photos/new.html.erb
<div class="container">
    <div class="card ">
        <div class="row photos_to_albums">
            <div class="col-sm-8">
                <%= form_for @photo, html: {class: "form-horizontal"} do |f| %>
                    <div class="form-group">
                            <%= f.label :title, "Title of Picture", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
                        </div>
                    </div>
                    <div class="form-group">
                            <%= f.label :desc, "Description", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :desc, class: "form-control", placeholder: "Enter description" %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="picture">
                            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/jpg" %>
                        </div>
                    </div>

                    <%= f.select :status, options_for_select([["Public", "1"],["Private", "0"] ]), :class => 'genForm_dropBox' %>


                    <div class="form-group">
                        <div class="col-md-10">
                            <%= f.submit "Upload", class: "btn btn-success" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>