railsapp/config/routes.rb
Rails.application.routes.draw do

  #devise login signup
  devise_for :users
  #edit-user
  post "users/edit_profiles", to: "users#edit_profiles",as: 'users/edit_profiles'

  #root
  root 'photos#index'

  #photos
  get 'new', to: 'photos#new'
  delete 'photos/:id', to: 'photos#destroy', as: 'photos/destroy'
  
  #albums
  get "albums/add/:id", to: "albums#add", as: 'albums/add'
  #photos, albums
  resources :photos , :albums
  # profiles
  get 'profiles/albums/:id', to: 'profiles#show_albums', as: 'profiles/album'
  get 'profiles/show/:id', to: 'profiles#show', as: 'profiles/show'
  get 'profiles/following/:id', to: 'profiles#show_following', as: 'profiles/following'
  get 'profiles/follower/:id', to: 'profiles#show_follower', as: 'profiles/follower'
  post 'profiles/following-connect/:id', to: 'profiles#follow_connect', as: 'profile/following-connect'
  delete 'profiles/following-delete/:id', to: 'profiles#follow_destroy', as:'profile/following-delelte'
  
  #reaction
  get "reactions/react-photo/:id", to: "reactions#react_photo", as: 'reactions/react-photo'
  get "reactions/unreact-photo/:id", to: "reactions#unreact_photo", as: 'reactions/unreact-photo'
  get "reactions/react-album/:id", to: "reactions#react_album", as: 'reactions/react-album'
  get "reactions/unreact-album/:id", to: "reactions#unreact_album", as: 'reactions/unreact-album'

  #discover
  get "discover/photos", to: "discover#show_photos", as: 'discover/photos'
  get "discover/albums", to: "discover#show_albums", as: 'discover/albums'
end

railsapp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def show_albums
        @user = User.find(params[:id])
        @albums = @user.albums.all.page params[:page]
    end

    def show
        @user = User.find(params[:id])
    end

    def show_follower
        @user = User.find(params[:id])
        @followers= @user.following.all.page params[:page]
    end

    def show_following
        @user = User.find(params[:id])
        @followers= @user.follower.all.page params[:page]
    end

    def follow_connect
        User.find(params[:id]).following << current_user
        redirect_to profiles_following_path(current_user)
    end

    def follow_destroy
        user=User.find(params[:id])
        user.following.delete current_user
        current_user.follower.delete user
        redirect_to profiles_following_path(current_user)
    end
end

railsapp/app/helpers/profiles_helper.rb
module ProfilesHelper
end

railsapp/app/views/profiles/show.html.erb
<div class="container-fluid">
  <div class="row pt-1 out-card">
    <div class="col-lg-2 col-md-2 col-sm-2 col-12">
      <ul class="list mt-4 submenu ">
        <li><%= link_to "Feed",  photos_path, class: 'feed-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'discover-submenu' %></li>
      </ul>
    </div>
    <div class="col-lg-8 col-md-11 col-sm-11 col-12 p-0 mid-col mb-4">
      <div class="row p-5">
        <div class="col-lg-12 col-md-12 col-12">
          <div class="info-top">
            <div class="row">
              <div class="col-lg-3 col-3">
                <div class="avatar">
                  <img src= <%= @user.avatar_url%> alt="">
                </div>
              </div>
              <div class="col-lg-9 col-9 p-0">
                <div class="col-lg-12 col-12">
                  <div class="following">
                    <% if @user == current_user%>
                      <%= link_to edit_user_registration_path do %>
                      <div class="custom-btn">Edit profile</div>
                      <%end%>   
                    <%else%>
                      <% if @user.following.include? current_user%>
                        <div class="custom-btn"> <%= link_to  "Unfollow", profile_following_delelte_path, method: :delete %></div>
                      <%else%>
                        <div class="custom-btn"> <%= link_to  "Follow", profile_following_connect_path,  method: :post%></div>
                      <%end%>
                    <%end%>
                </div>
              </div>
              <div class="col-lg-12 col-12 mt-4">
                <div class="name pt-2">
                  <h1><%= @user.lname%>&nbsp;<%=@user.fname%></h1>
                </div>
              </div>
              <div class="col-lg-12 col-12 mt-3 d-flex">
                <ul class= profiles-link>            
                  <li> <%=@user.photos_count %>  <%= link_to 'Photos',profiles_show_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.albums_count %>  <%= link_to 'ALbums',profiles_album_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.following_count %>  <%= link_to 'Following',profiles_following_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.follower_count %>  <%= link_to 'Follower',profiles_follower_path(@user.id) %>&nbsp;&verbar;</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% if @user == current_user%> 
      <div class="col-lg-12 col-md-12 col-12 mt-2">
        <div class="following addphoto-but">
          <%= link_to new_photo_path do %>
            <div class="custom-btn-addphoto">Add photo</div>
          <%end%>
        </div>
      </div>
    <%end%>
      <div class="col-lg-12 col-md-12 col-12 mt-4">
        <div class="row">
          <% @user.photos.each do |photo|%>
            <% if @user== current_user%>
              <div class="col-12 col-md-3">
                <i class=" edit-lock"><%= link_to  "Edit", edit_photo_path(photo), class: "edit-lock-1" %></i>
                <img alt="picture" src= <%= photo.image_url(:thumb)%> class="img-fluid">
                <% if photo.status?%>
                  <i class="fas fa-unlock-alt lock"></i>
                <% else%>
                  <i class="fas fa-lock lock"></i> 
                <%end%>
                <h4> <%= photo.title%></h4>
             </div>
            <%else%>
              <% if photo.status?%>
                <img alt="picture" src= <%= photo.image_url(:thumb)%> class="img-fluid">
              <%end%>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </div>

railsapp/app/views/profiles/show_albums.html.erb
<div class="container-fluid">
  <div class="row pt-1 out-card">
     <div class="col-lg-2 col-md-2 col-sm-2 col-12">
        <ul class="list mt-4 submenu ">
        <li><%= link_to "Feed",  photos_path, class: 'feed-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'discover-submenu' %></li>
      </ul>
    </div>
    <div class="col-lg-8 col-md-11 col-sm-11 col-12 p-0 mid-col mb-4">
      <div class="row p-5">
        <div class="col-lg-12 col-md-12 col-12">
          <div class="info-top">
            <div class="row">
              <div class="col-lg-3 col-3">
                <div class="avatar">
                  <img src= <%= @user.avatar_url%> alt="">
                </div>
              </div>
              <div class="col-lg-9 col-9 p-0">
                <div class="col-lg-12 col-12">
                  <div class="following">
                    <% if @user == current_user%>
                    <div class="custom-btn">Edit profile</div>
                    <%else%>
                       <% if @user.following.include? current_user%>
                           <div class="custom-btn"> <%= link_to  "Unfollow", profile_following_delelte_path, method: :delete %></div>
                      <%else%>
                           <div class="custom-btn"> <%= link_to  "Follow", profile_following_connect_path,  method: :post%></div>
                      <%end%>
                    <%end%>
                  </div>
                </div>
              <div class="col-lg-12 col-12 mt-4">
                <div class="name pt-2">
                  <h1><%= @user.lname%>&nbsp;<%=@user.fname%></h1>
                </div>
              </div>
              <div class="col-lg-12 col-12 mt-3 d-flex">
                <ul class= profiles-link>            
                  <li> <%=@user.photos_count %>  <%= link_to 'Photos',profiles_show_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.albums_count %>  <%= link_to 'ALbums',profiles_album_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.following_count %>  <%= link_to 'Following',profiles_following_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.follower_count %>  <%= link_to 'Follower',profiles_follower_path(@user.id) %>&nbsp;&verbar;</li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
     <% if @user == current_user%>
    <div class="col-lg-12 col-md-12 col-12 mt-2">
      <div class="following addphoto-but">
          <%= link_to new_album_path do %>
            <div class="custom-btn-addphoto">Add Album</div>
           <%end%>
        </div>
    </div>
    <%end%>
    <div class="col-lg-12 col-md-12 col-12 mt-4">

      <div class="row">
      <% @albums.each do |album|%>
        <% if @user == current_user%>
          <div class="col-12 col-md-3 mt-3">
          <div>
            <div class="photo-contain">
              <img alt="picture" src= <%= album.photos.take.image_url(:medium)%> class="img-fluid photo1">
              <img alt="picture" src= <%= album.photos.take.image_url(:medium)%> class="img-fluid photo2">
              <img alt="picture" src= <%= album.photos.take.image_url(:medium)%> class="img-fluid photo3">
            </div>
          </div>   
          <i class=" edit-lock-album"><%= link_to  "Edit", edit_album_path(album), class: "edit-lock-1" %></i>
          <p class="photo-size">
            <p class="photo-size-count"> <%= album.photos_count%></p>
            <p class="photo-size-p"> Photos</p>
          </p>
          <% if album.status?%>
            <i class="fas fa-unlock-alt lock-album"></i>
          <% else%>
            <i class="fas fa-lock lock-album"></i> 
          <%end%>

        <% else%>
          <div class="col-12 col-md-3 mt-3">
          <div>
            <div class="photo-contain">
              <img alt="picture" src= <%= album.photos.take.image_url(:medium)%> class="img-fluid photo1">
              <img alt="picture" src= <%= album.photos.take.image_url(:medium)%> class="img-fluid photo2">
              <img alt="picture" src= <%= album.photos.take.image_url(:medium)%> class="img-fluid photo3">
            </div>
          </div>
          <p class="photo-size">
            <p class="photo-size-count"> <%= album.photos_count%></p>
            <p class="photo-size-p"> Photos</p>
          </p>
         <%end%>
        <h4> <%= album.title%></h4>
      </div>
    <%end%>
    </div>
  </div>
</div>

railsapp/app/views/profiles/show_follower.html.erb
<div class="container-fluid">
  <div class="row pt-1 out-card">
    <div class="col-lg-2 col-md-2 col-sm-2 col-12">
        <ul class="list mt-4 submenu ">
        <li><%= link_to "Feed",  photos_path, class: 'feed-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'discover-submenu' %></li>
      </ul>
    </div>
    <div class="col-lg-8 col-md-11 col-sm-11 col-12 p-0 mid-col mb-4">
      <div class="row p-5">
        <div class="col-lg-12 col-md-12 col-12">
          <div class="info-top">
            <div class="row">
              <div class="col-lg-3 col-3">
                <div class="avatar">
                  <img src= <%= @user.avatar_url%> alt="">
                </div>
              </div>
              <div class="col-lg-9 col-9 p-0">
                <div class="col-lg-12 col-12">
                  <div class="following">
                  <% if @user == current_user%>
                    <div class="custom-btn">Edit profile</div>
                    <%else%>
                       <% if @user.following.include? current_user%>
                           <div class="custom-btn"> <%= link_to  "Unfollow", profile_following_delelte_path, method: :delete %></div>
                      <%else%>
                           <div class="custom-btn"> <%= link_to  "Follow", profile_following_connect_path,  method: :post%></div>
                      <%end%>
                    <%end%>
                  </div>
                </div>
              <div class="col-lg-12 col-12 mt-4">
                <div class="name pt-2">
                  <h1><%= @user.lname%>&nbsp;<%=@user.fname%></h1>
                </div>
              </div>
              <div class="col-lg-12 col-12 mt-3 d-flex">
               <ul class= profiles-link>            
                  <li> <%=@user.photos_count %>  <%= link_to 'Photos',profiles_show_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.albums_count %>  <%= link_to 'ALbums',profiles_album_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.following_count %>  <%= link_to 'Following',profiles_following_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.follower_count %>  <%= link_to 'Follower',profiles_follower_path(@user.id) %>&nbsp;&verbar;</li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
     <div class="col-lg-12 col-md-12 col-12 mt-4">
      <div class="row">
      <% @followers.each do |follow|%>
        <div class="col-12 col-md-3">
            <div class="items mt-3 mb-3">
                <div class="avatar mb-1">
                    <img src="https://picsum.photos/300" alt="">
                </div>
                <div class="name mb-2">
                <%= link_to profiles_show_path(follow.id) do %>
                <%= follow.lname %><%= follow.fname%>
                 <%end%>
                </div>
                <div class="number d-flex justify-content-between">
                    <div class="photo">
                        <span class="number"><%= follow.photos_count %></span>
                        <span class="type">photo</span>
                    </div>

                    <div class="album mb-2">
                        <span class="number"><%= follow.albums_count %></span>
                        <span class="type">album</span>
                    </div>
                </div>
                <div class="flw">

                 <% if follow == current_user%>
                      <div class="custom-btn-following invisible"> <%= link_to  "Unfollow", profile_following_delelte_path(follow.id), method: :delete %></div>
                <%else%>
                    <% if follow.following.include? current_user%>
                      <div class="custom-btn-following"> <%= link_to  "Unfollow", profile_following_delelte_path(follow.id), method: :delete %></div>
                      <%else%>
                      <div class="custom-btn-following"> <%= link_to  "Follow", profile_following_connect_path(follow.id),  method: :post%></div>
                      <%end%>
                <%end%>
                </div>
            </div>
        </div>
      <%end%>
    </div>
    </div>
  </div>
</div>

railsapp/app/views/profiles/show_following.html.erb
<div class="container-fluid">
  <div class="row pt-1 out-card">
    <div class="col-lg-2 col-md-2 col-sm-2 col-12">
        <ul class="list mt-4 submenu ">
        <li><%= link_to "Feed",  photos_path, class: 'feed-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'discover-submenu' %></li>
      </ul>
    </div>
    <div class="col-lg-8 col-md-11 col-sm-11 col-12 p-0 mid-col mb-4">
      <div class="row p-5">
        <div class="col-lg-12 col-md-12 col-12">
          <div class="info-top">
            <div class="row">
              <div class="col-lg-3 col-3">
                <div class="avatar">
                  <img src= <%= @user.avatar_url%> alt="">
                </div>
              </div>
              <div class="col-lg-9 col-9 p-0">
                <div class="col-lg-12 col-12">
                  <div class="following">
                 <% if @user == current_user%>
                    <div class="custom-btn">Edit profile</div>
                    <%else%>
                       <% if @user.following.include? current_user%>
                           <div class="custom-btn"> <%= link_to  "Unfollow", profile_following_delelte_path, method: :delete %></div>
                      <%else%>
                           <div class="custom-btn"> <%= link_to  "Follow", profile_following_connect_path,  method: :post%></div>
                      <%end%>
                    <%end%>
                  </div>
                </div>
              <div class="col-lg-12 col-12 mt-4">
                <div class="name pt-2">
                  <h1><%= @user.lname%>&nbsp;<%=@user.fname%></h1>
                </div>
              </div>
              <div class="col-lg-12 col-12 mt-3 d-flex">
               <ul class= profiles-link>            
                  <li> <%=@user.photos_count %>  <%= link_to 'Photos',profiles_show_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.albums_count %>  <%= link_to 'ALbums',profiles_album_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.following_count %>  <%= link_to 'Following',profiles_following_path(@user.id) %>&nbsp;&verbar;</li>
                  <li> <%=@user.follower_count %>  <%= link_to 'Follower',profiles_follower_path(@user.id) %>&nbsp;&verbar;</li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
     <div class="col-lg-12 col-md-12 col-12 mt-4">
      <div class="row">
      <% @followers.each do |follow|%>
        <div class="col-12 col-md-3">
            <div class="items mt-3 mb-3">
                <div class="avatar mb-1">
                    <img src="https://picsum.photos/300" alt="">
                </div>
                <div class="name mb-2">
                <%= link_to profiles_show_path(follow.id) do %>
                <%= follow.lname %><%= follow.fname%>
                 <%end%>
                </div>
                <div class="number d-flex justify-content-between">
                    <div class="photo">
                        <span class="number"><%= follow.photos_count %></span>
                        <span class="type">photo</span>
                    </div>

                    <div class="album mb-2">
                        <span class="number"><%= follow.albums_count %></span>
                        <span class="type">album</span>
                    </div>
                </div>
                <div class="flw">
                 <% if follow == current_user%>
                      <div class="custom-btn-following invisible"> <%= link_to  "Unfollow", profile_following_delelte_path(follow.id), method: :delete %></div>
                    <%else%>
                    <div class="custom-btn-following"> <%= link_to  "Unfollow", profile_following_delelte_path(follow.id), method: :delete %></div>
                    <%end%>
                </div>
            </div>
        </div>
      <%end%>
    </div>
    </div>
  </div>
</div>