railsapp/config/routes.rb
Rails.application.routes.draw do

  #devise login signup
  devise_for :users
  #edit-user
  post "users/edit_profiles", to: "users#edit_profiles",as: 'users/edit_profiles'

  #root
  root 'photos#index'

  #photos
  get 'new', to: 'photos#new'
  delete 'photos/:id', to: 'photos#destroy', as: 'photos/destroy'
  
  #albums
  get "albums/add/:id", to: "albums#add", as: 'albums/add'
  #photos, albums
  resources :photos , :albums
  # profiles
  get 'profiles/albums/:id', to: 'profiles#show_albums', as: 'profiles/album'
  get 'profiles/show/:id', to: 'profiles#show', as: 'profiles/show'
  get 'profiles/following/:id', to: 'profiles#show_following', as: 'profiles/following'
  get 'profiles/follower/:id', to: 'profiles#show_follower', as: 'profiles/follower'
  post 'profiles/following-connect/:id', to: 'profiles#follow_connect', as: 'profile/following-connect'
  delete 'profiles/following-delete/:id', to: 'profiles#follow_destroy', as:'profile/following-delelte'
  
  #reaction
  get "reactions/react-photo/:id", to: "reactions#react_photo", as: 'reactions/react-photo'
  get "reactions/unreact-photo/:id", to: "reactions#unreact_photo", as: 'reactions/unreact-photo'
  get "reactions/react-album/:id", to: "reactions#react_album", as: 'reactions/react-album'
  get "reactions/unreact-album/:id", to: "reactions#unreact_album", as: 'reactions/unreact-album'

  #discover
  get "discover/photos", to: "discover#show_photos", as: 'discover/photos'
  get "discover/albums", to: "discover#show_albums", as: 'discover/albums'
end

railsapp/app/models/album.rb
class Album < ApplicationRecord
    has_many :albums_photos,dependent: :destroy
    has_many :photos, through: :albums_photos
   
    belongs_to :user, counter_cache: :albums_count
    has_many :reactions, as: :react , dependent: :destroy

    #upload file
    # validates :title, :desc, :status, :collection, presence: true
    # validates :title, presence: true ,length: {minimum:4,maximum:140}
    # validates :status, acceptance: {accept: ['0','1']}
    # validates :desc, length: {maximum:300}
    # validates :collection, numericality: {more_than: 1, less_than:25}

end 

railsapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_id_album, only: [:show,:edit, :update, :destory]

    def index
      if current_user
        @albums= Album.joins("INNER JOIN follows ON follows.follower_id = user_id").where("follows.followed_id = :id", id: current_user.id).includes(:user,:reactions).page params[:page]
      else
          @albums = Album.where("status = ?",'1').order(:created_at).includes(:user).page params[:page]
      end
    end

    def new
      @album =Album.new
    end
    
    def create
      @album = current_user.albums.new params_album
      @photo = current_user.photos.new params_photo
      @rela= @album.albums_photos.new(photo: @photo)
      if @rela.save && @album.save  && @photo.save)
        flash[:success] = "Upload album success"
        redirect_to albums_path
      else
        flash[:danger] = "Upload failed"
        render :new
      end
    end

    def edit
      @photo = @album.photos.all
    end
    
    def update
      @photo = current_user.photos.new params_photo
      @rela= @album.albums_photos.new(photo: @photo)
      if @album.update(params_album) &&  @rela.save
        flash[:success] = 'The album has just updated'
        redirect_to profiles_album_path(current_user)
      else
        render 'edit'
      end
    end
    
    def destroy
      @album.destroy
    end
  
    private
      def find_id_album
        @album = Album.find(params[:id])
      end

      def params_album
        params.require(:album ).permit(:title,:desc,:status)
      end
      def params_photo
        params.require(:album ).permit(:title, :desc,:status,:image)
      end

end

railsapp/app/helpers/albums_helper.rb
module AlbumsHelper
end

railsapp/app/views/albums/edit.html.erb
<div class="container">
    <div class="card ">
        <div class="row photos_to_albums">
            <div class="col-sm-8">
                <%= form_for @album, html: {class: "form-horizontal"} do |f| %>
                    <div class="form-group">
                            <%= f.label :title, "Title of Picture", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
                        </div>
                    </div>
                    <div class="form-group">
                            <%= f.label :desc, "Description", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :desc, class: "form-control", placeholder: "Enter description" %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="picture">
                            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/jpg" %>
                        </div>
                    </div>

                    <%= f.select :status, options_for_select([["Public", "1"],["Private", "0"] ]), :class => 'genForm_dropBox' %>


                    <div class="form-group">
                        <div class="col-md-10">
                            <%= f.submit "Update", class: "btn btn-success" %>
                        </div>
                    </div>
                    
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <% @photo.each do |photo|%>
            <div class="col-12 col-sm-4 photos_to_albums">
                <img src=<%=photo.image%>>
                <div> <%= link_to  "Delete", photos_destroy_path(photo.id), method: :delete  %></div>
               
            </div>
        <% end %>
    </div>
</div>

railsapp/app/views/albums/index.html.erb
<div class="container-fluid cus-body-color">
  <div class="row">
    <div class="col-12 col-sm-2 sticky-top ">
      <ul class="list mt-4 submenu  sticky-top">
        <li><%= link_to "Feed",  photos_path, class: 'feed-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'discover-submenu' %></li>
      </ul>
    </div>
    <div class="col-12 col-sm-8 pt-4 cus-card-color">
      <div class="photos_to_albums">
        <div class="btn-group btn-group-lg but" role="group" aria-label="Basic example">
          <button type="button" class="btn pagebut "style="border: 2px solid #3c5a96"><%= link_to "Photos", photos_path, {style: 'font-size: 20px;  color: #3c5a96 ; text-decoration: none' } %></button>
          <button type="button" class="btn pagebut" style="background:#3c5a96; color:#FFF" >Albums</button>
        </div>
      </div>

      <div class="container cus-main op">
        <div class="row mt-4">
          <% @albums.find_each do |album|%>
          <div class="col-12 col-sm-12 col-md-12 col-lg-6 photo-container">
            <div class="card mb-3 shadow" style="max-width: 540px;">
              <div class="row no-gutters">
                <div class="col-md-12 col-lg-7">
                  <img src=<%=album.photos.take.image_url(:thumb) %> class="card-img cus photo1" alt="..." data-toggle="modal" data-target="#mod">
                  <img src=<%=album.photos.take.image_url(:thumb) %> class="card-img photo2" alt="Photo">
                  <img src=<%=album.photos.take.image_url(:thumb) %> class="card-img photo3" alt="Photo">
                </div>

                <div class="col-md-12 col-lg-5">
                  <div class="card-body cus-body">
                    <div  class="user d-flex">
                        <div class="image"> 
                          <%=album.user.fname.slice(0)+album.user.lname.slice(0)%>
                        </div>
                      <%= link_to profiles_show_path(album.user.id) do %> 
                      <span class=" "><%= album.user.fname%> <%=album.user.lname %></span>
                      <% end%>  
                    </div>  
                    <h5 class="card-title custitle" ><%= album.title%></h5>
                    <p class="card-text cusdesc " ><%= album.desc%></p>
                  </div>
                  <div>
                  <% if user_signed_in? %>
                    <% if album.reactions.exists? user_id: current_user.id%>
                        <%= link_to reactions_unreact_album_path(album.id) do %>
                          <i class="fas fa-heart fa-1x">&nbsp;<%= album.reactions.size%></i>
                        <% end%> 
                      <%else%>
                        <%= link_to reactions_react_album_path(album.id) do %>
                          <i class="far fa-heart fa-1x">&nbsp;<%= album.reactions.size%></i>
                        <% end%> 
                      <% end%> 
                  <% end%>
                    <i class="card-text"><small class="cusdate pt-1"><%= album.created_at%></small></i>
                  </div>
                </div>

              </div>
            </div>
          </div>
            <% end%>
        </div>
      </div>
    </div>
  </div>
</div>
             


<!-- Modal -->
<div class="modal fade" id="mod" tabindex="-1" role="dialog" aria-labelledby="modal-title-id" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-title-id">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="..." alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="..." alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="..." alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
      <div class="modal-footer">
       <p id="modal-desc"></p>
      </div>
    </div>
  </div>
</div>
<div class="photos_to_albums"> <%= paginate @albums, theme: 'twitter-bootstrap-4' %></div>

railsapp/app/views/albums/new.html.erb
<div class="container">
    <div class="card ">
        <div class="row photos_to_albums">
            <div class="col-sm-8">
                <%= form_for @album, html: {class: "form-horizontal"} do |f| %>
                    <div class="form-group">
                            <%= f.label :title, "Title of Picture", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
                        </div>
                    </div>
                    <div class="form-group">
                            <%= f.label :desc, "Description", class: "col-md-2 control-label" %>
                        <div class="col-md-10">
                            <%= f.text_field :desc, class: "form-control", placeholder: "Enter description" %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="picture">
                            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/jpg" %>
                        </div>
                    </div>

                    <%= f.select :status, options_for_select([["Public", "1"],["Private", "0"] ]), :class => 'genForm_dropBox' %>


                    <div class="form-group">
                        <div class="col-md-10">
                            <%= f.submit "Upload", class: "btn btn-success" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>