railsapp/config/routes.rb
Rails.application.routes.draw do

  #devise login signup
  devise_for :users
  #edit-user
  post "users/edit_profiles", to: "users#edit_profiles",as: 'users/edit_profiles'

  #root
  root 'photos#index'

  #photos
  get 'new', to: 'photos#new'
  delete 'photos/:id', to: 'photos#destroy', as: 'photos/destroy'
  
  #albums
  get "albums/add/:id", to: "albums#add", as: 'albums/add'
  #photos, albums
  resources :photos , :albums
  # profiles
  get 'profiles/albums/:id', to: 'profiles#show_albums', as: 'profiles/album'
  get 'profiles/show/:id', to: 'profiles#show', as: 'profiles/show'
  get 'profiles/following/:id', to: 'profiles#show_following', as: 'profiles/following'
  get 'profiles/follower/:id', to: 'profiles#show_follower', as: 'profiles/follower'
  post 'profiles/following-connect/:id', to: 'profiles#follow_connect', as: 'profile/following-connect'
  delete 'profiles/following-delete/:id', to: 'profiles#follow_destroy', as:'profile/following-delelte'
  
  #reaction
  get "reactions/react-photo/:id", to: "reactions#react_photo", as: 'reactions/react-photo'
  get "reactions/unreact-photo/:id", to: "reactions#unreact_photo", as: 'reactions/unreact-photo'
  get "reactions/react-album/:id", to: "reactions#react_album", as: 'reactions/react-album'
  get "reactions/unreact-album/:id", to: "reactions#unreact_album", as: 'reactions/unreact-album'

  #discover
  get "discover/photos", to: "discover#show_photos", as: 'discover/photos'
  get "discover/albums", to: "discover#show_albums", as: 'discover/albums'
end

railsapp/app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
    before_action :authenticate_user!
    def show_photos
        @photo = Photo.where("status = ?",'1').order(:created_at).includes(:user).page params[:page]    
    end
    def show_albums
        @albums = Album.where("status = ?",'1').order(:created_at).includes(:user).page params[:page]  
    end
    
    
end

railsapp/app/helpers/discover_helper.rb
module DiscoverHelper
end

railsapp/app/views/discover/show_albums.html.erb
<div class="container-fluid cus-body-color">
  <div class="row">
    <div class="col-12 col-sm-2 sticky-top ">
      <ul class="list mt-4 submenu  sticky-top">
        <li><%= link_to "Feed",  photos_path,class: 'discover-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path,class: 'feed-submenu'  %></li>
      </ul>
    </div>
    <div class="col-12 col-sm-8 pt-4 cus-card-color">
      <div class="photos_to_albums">
        <div class="btn-group btn-group-lg but" role="group" aria-label="Basic example">
          <button type="button" class="btn pagebut "style="border: 2px solid #3c5a96"><%= link_to "Photos", discover_photos_path, {style: 'font-size: 20px;  color: #3c5a96 ; text-decoration: none' } %></button>
          <button type="button" class="btn pagebut" style="background:#3c5a96; color:#FFF" >Albums</button>
        </div>
      </div>

      <div class="container cus-main op">
        <div class="row mt-4">
          <% @albums.each do |album|%>
          <div class="col-12 col-sm-12 col-md-12 col-lg-6 photo-container">
            <div class="card mb-3 shadow" style="max-width: 540px;">
              <div class="row no-gutters">
                <div class="col-md-12 col-lg-7">
                  <img src=<%=album.photos.take.image_url(:thumb) %> class="card-img cus photo1" alt="..." data-toggle="modal" data-target="#mod">
                  <img src=<%=album.photos.take.image_url(:thumb) %> class="card-img photo2" alt="Photo">
                  <img src=<%=album.photos.take.image_url(:thumb) %> class="card-img photo3" alt="Photo">
                </div>

                <div class="col-md-12 col-lg-5">
                  <div class="card-body cus-body">
                    <div  class="user d-flex">
                        <div class="image"> 
                          <%=album.user.fname.slice(0)+album.user.lname.slice(0)%>
                        </div>
                      <%= link_to profiles_show_path(album.user.id) do %> 
                      <span class=" "><%= album.user.fname%> <%=album.user.lname %></span>
                      <% end%>  
                    </div>  
                    <h5 class="card-title custitle" ><%= album.title%></h5>
                    <p class="card-text cusdesc " ><%= album.desc%></p>
                  </div>
                  <div>
                  <% if user_signed_in? %>
                    <% if album.reactions.exists? user_id: current_user.id%>
                        <%= link_to reactions_unreact_album_path(album.id) do %>
                          <i class="fas fa-heart fa-1x">&nbsp;<%= album.reactions.size%></i>
                        <% end%> 
                      <%else%>
                        <%= link_to reactions_react_album_path(album.id) do %>
                          <i class="far fa-heart fa-1x">&nbsp;<%= album.reactions.size%></i>
                        <% end%> 
                      <% end%> 
                  <% end%>
                    <i class="card-text"><small class="cusdate pt-1"><%= album.created_at%></small></i>
                  </div>
                </div>

              </div>
            </div>
          </div>
            <% end%>
        </div>
      </div>
    </div>
  </div>
</div>
             


<!-- Modal -->
<div class="modal fade" id="mod" tabindex="-1" role="dialog" aria-labelledby="modal-title-id" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-title-id">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="..." alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="..." alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="..." alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
      <div class="modal-footer">
       <p id="modal-desc"></p>
      </div>
    </div>
  </div>
</div>
<div class="photos_to_albums"> <%= paginate @albums, theme: 'twitter-bootstrap-4' %></div>

railsapp/app/views/discover/show_photos.html.erb
<div class="container-fluid cus-body-color">
  <div class="row">
    <div class="col-12 col-sm-2 sticky-top ">
      <ul class="list mt-4 submenu ">
        <li><%= link_to "Feed",  photos_path, class: 'discover-submenu' %></li>
        <li><%= link_to "Discover",  discover_photos_path, class: 'feed-submenu' %></li>
      </ul>
    </div>
    <div class="col-12 col-sm-8 pt-4 cus-card-color">
      <div class="photos_to_albums">
        <div class="btn-group btn-group-lg but" role="group" aria-label="Basic example">
          <button type="button" class="btn pagebut " style="background:#3c5a96; color:#FFF">Photos</button>
          <button type="button" class="btn pagebut" style="border: 2px solid #3c5a96"><%= link_to "Albums", discover_albums_path, {style: 'font-size: 20px;  color: #3c5a96 ; text-decoration: none' } %></button>
        </div>
      </div>

      <div class="container cus-main op">
        <div class="row mt-4">
          <% @photo.each do |photo|%>
          <div class="col-12 col-sm-12 col-md-12 col-lg-6 photo-container">
            <div class="card mb-3 shadow" style="max-width: 540px;">
              <div class="row no-gutters">
                <div class="col-md-12 col-lg-7">
                  <img src=<%= photo.image_url(:thumb)%> class=" cus" alt="..." data-toggle="modal" data-target="#mod">
                </div>

                <div class="col-md-12 col-lg-5">
                  <div class="card-body cus-body">
                 
                    <div  class="user d-flex">
                        <div class="image"> 
                          <%=photo.user.fname.slice(0)+photo.user.lname.slice(0)%>
                        </div>
                         <%= link_to profiles_show_path(photo.user.id) do %> 
                      <span class=" "><%= photo.user.fname%> <%=photo.user.lname %></span>
                      <% end%>
                      
                        <% if photo.user.following.include? current_user%>
                           <div class="custom-btn-following"> <%= link_to  "Unfollow", profile_following_delelte_path(photo.user_id), method: :delete %></div>
                        <%else%>
                           <div class="custom-btn-following"> <%= link_to  "Follow", profile_following_connect_path(photo.user_id),  method: :post%></div>
                        <%end%>
                    </div>
                     
                    <h5 class="card-title custitle" ><%= photo.title%></h5>
                    <p class="card-text cusdesc " ><%= photo.desc%></p>
                  </div>
                  <div>
                      <% if photo.reactions.exists? user_id: current_user.id%>
                        <%= link_to reactions_unreact_photo_path(photo.id) do %>
                          <i class="fas fa-heart fa-1x">&nbsp;<%= photo.reactions.size%></i>
                        <% end%> 
                      <%else%>
                        <%= link_to reactions_react_photo_path(photo.id) do %>
                          <i class="far fa-heart fa-1x">&nbsp;<%= photo.reactions.size%></i>
                        <% end%> 
                      <% end%> 

                    <i class="card-text"><small class="cusdate pt-1"><%= photo.created_at%></small></i>
                  </div>
                </div>

              </div>
            </div>
          </div>
            <% end%>
        </div>
      </div>
    </div>
  </div>
</div>
             


<!-- Modal -->
<div class="modal fade" id="mod" tabindex="-1" role="dialog" aria-labelledby="modal-title-id" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-title-id">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img id="modal-img" src="" alt="..." style="width:100%;height:auto">
      </div>
      <div class="modal-footer">
       <p id="modal-desc"></p>
      </div>
    </div>
  </div>
</div>
<div class="photos_to_albums"> <%= paginate @photo, theme: 'twitter-bootstrap-4' %></div>